name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "cuong@example.com"
          git config --global user.name "Cuong2004"
          # Use a temporary directory to avoid git-in-git issues
          mkdir hf_copy
          cp -r backend/* hf_copy/
          cd hf_copy
          git init
          git remote add origin https://Cuong2004:$HF_TOKEN@huggingface.co/spaces/Cuong2004/math-solver
          git add .
          git commit -m "Deploy from GitHub Actions"
          git push --force origin master:main
